# Generated by Django 3.1.7 on 2021-03-04 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mobileNo', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('departmentType', models.CharField(choices=[('Crop Department', 'Crop Department'), ('Seeds Department', 'Seeds Department'), ('Workers Department', 'Workers Department')], default='Crop Department', max_length=40)),
                ('profileImage', models.ImageField(default='', upload_to='management/employeeProfile/')),
                ('address', models.CharField(max_length=150)),
                ('ability', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='pesticidesModel',
            fields=[
                ('pesticides_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=30)),
                ('pesticides_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='seedsModel',
            fields=[
                ('seeds_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=30)),
                ('seeds_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='crop',
            name='cropSeason',
            field=models.CharField(choices=[('Monsoon(Kharif Crop)', 'Monsoon(Kharif Crop)'), ('Winter(Rabi Crop)', 'Winter(Rabi Crop)'), ('Summer(Zaid Crop)', 'Summer(Zaid Crop)')], default='Monsoon(Kharif Crop)', max_length=40),
        ),
        migrations.AlterField(
            model_name='crop',
            name='cropType',
            field=models.CharField(choices=[('FoodCrop(Grains)', 'FoodCrop(Grains)'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Non FoodCrop', 'Non FoodCrop')], default='FoodCrop(Grains)', max_length=40),
        ),
    ]
