# Generated by Django 3.1.6 on 2021-02-10 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('mobileNo', models.IntegerField(default=0)),
                ('farmaddress', models.TextField(default='')),
                ('farmArea', models.IntegerField(default=0)),
                ('soilType', models.TextField(default='')),
                ('moneyDemand', models.IntegerField(default=0)),
                ('farmImage', models.ImageField(default='', upload_to='user/farm')),
                ('extraComment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
