# Generated by Django 3.1.6 on 2021-02-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='mobileNo',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
