# Generated by Django 3.1.6 on 2021-02-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210210_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecord',
            old_name='userId',
            new_name='recordId',
        ),
    ]
