# Generated by Django 3.1.6 on 2021-02-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210212_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='farmImage',
            field=models.ImageField(default='', upload_to='user/farm/'),
        ),
    ]
