# Generated by Django 3.1.6 on 2021-02-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210212_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='farmImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
