# Generated by Django 3.1.6 on 2021-02-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210212_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='farmImage',
            field=models.ImageField(upload_to='user/farm/'),
        ),
    ]
