# Generated by Django 3.1.6 on 2021-02-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210213_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='farmaddress',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='mobileNo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='soilType',
            field=models.CharField(choices=[('Sandy soil', 'Sandy Soil'), ('Silt Soil', 'Silt Soil'), ('Clay Soil', 'Clay Soil'), ('Loamy Soil', 'Loamy Soil')], default='Silt Soil', max_length=11),
        ),
    ]
