# Generated by Django 3.1.6 on 2021-02-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_edituserprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edituserprofile',
            old_name='farmImage',
            new_name='Change_photo',
        ),
    ]
