# Generated by Django 3.1.6 on 2021-02-16 11:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0016_auto_20210216_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='editUserProfile',
            new_name='UserProfile',
        ),
    ]
