# Generated by Django 3.1.6 on 2021-02-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210216_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Change_photo',
            new_name='Changephoto',
        ),
    ]
