# Generated by Django 3.1.6 on 2021-02-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210217_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Changephoto',
            field=models.ImageField(default='', upload_to='user/profile_pic/'),
        ),
    ]
