# Generated by Django 3.1.6 on 2021-02-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210217_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Changephoto',
            field=models.ImageField(default='', upload_to='user/profilepic/'),
        ),
    ]
