# Generated by Django 3.1.6 on 2021-02-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210217_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
