# Generated by Django 3.1.7 on 2021-02-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20210220_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ProfilePic',
            field=models.ImageField(blank=True, default='media/user/profilePics/defaultpic.jpg', null=True, upload_to='user/profilePics/'),
        ),
    ]
