# Generated by Django 3.1.7 on 2021-02-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20210221_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ProfilePic',
            field=models.ImageField(blank=True, default='user/profilePics/defaultpic.jpg', null=True, upload_to='user/profilePics/'),
        ),
    ]
