# Generated by Django 3.1.7 on 2021-03-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210304_2002'),
        ('user', '0029_userrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='crop',
            field=models.ManyToManyField(blank=True, to='management.crop'),
        ),
    ]
