# Generated by Django 3.1.7 on 2021-04-01 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210304_2002'),
        ('user', '0031_auto_20210311_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='cropArea',
            fields=[
                ('crQ_id', models.AutoField(primary_key=True, serialize=False)),
                ('Area', models.PositiveIntegerField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.crop')),
                ('userRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userrecord')),
            ],
        ),
    ]
